[Refactor] vite 제거, types 디렉토리 이동, store 디렉토리 이동
wafflestudio/ggzz-client pull request #3
Opened 2023-05-01 09:39 UTC by iihyungsuk

## 태스크 URL

[노션 이슈 링크](https://www.notion.so/wafflestudio/f8316de46fb5469eb9c2a0a20dd808ae?pvs=4)

## 체크리스트
- [ ] pre-commit 성공 여부
- [ ] yarn build 성공 여부
- [x ] Type label 추가

## 설명
코드 리팩토링했습니다. 형욱이 형 작업하기 전에 했어야 했는데 하하.. 죄송합니다.
변경 내용 아래와 같습니다.
1. vite 관련 파일 제거 후 대체
2. package.json에서 vite 관련 내용 삭제 후 해당 부분 create-react-app시 설정되는 기본 설정으로 대체. 
이후 아래 내용 실행함.
```bash
rm -rf node_modules yarn.lock
```
3. types 디렉토리 => lib 디렉토리 내부로 병합시킴
4. store 디렉토리 => src 디렉토리 내부로 이동시킴
5. 기타 자잘한 수정사항들

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-05-02 09:27 UTC, GoGiants1 requested changes
메인 브랜치 리베이스 부탁드려용
[참고](https://velog.io/@pock11/git-rebase-%ED%95%98%EB%8A%94-%EB%B2%95)

2023-05-02 13:41 UTC, iihyungsuk commented
main에 rebase 진행하였습니다.
테스트할 때 아래와 같이 부탁드립니다.
```bash
rm -rf node_modules
yarn
yarn start
```

2023-05-04 07:50 UTC, iihyungsuk commented
@andhl204 @designDefined @GoGiants1  최종 리뷰 부탁드립니다.

2023-05-04 07:56 UTC, GoGiants1 approved these changes
머지하시죠~~
(+ 이번 리팩토링은 스쿼시 앤 머지 말고, 리베이스 & 머지로 했으면 좋겠습니다.)

2023-05-04 14:38 UTC, iihyungsuk commented
머지하면
.env 파일
VITE_GOOGLE_MAP_API_KEY 변수명
VITE => REACT_APP 로 고쳐야 함.

2023-05-05 10:34 UTC, merged